apiVersion: v1
kind: Service
metadata:
  name: vscode-test
spec:
  ports:
  - name: http-listener
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: http-port-1
    port: 3000
    protocol: TCP
    targetPort: 3000
  - name: http-port-2
    port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    app.kubernetes.io/name: vscode-test
  sessionAffinity: None
  type: NodePort
